### ISSUE TITLE
Catalina flags ISOBMFF-Dump as malware

### ISSUE THREAD

**Issue by jchudzynski** [DigiDNA/ISOBMFF#16] opened 2020-04-19 21:46 UTC
![image](https://user-images.githubusercontent.com/1026574/79700686-3e7a6700-825d-11ea-80c9-d177495990e9.png)

**Comment by macmade** [comment] 2020-04-20 13:20
Thanks for the report.
I was not able to reproduce this particular issue, but that's true that the standalone version has some issues with the new permission system of macOS 10.15.

You may use the AppStore version instead, which isn't impacted by those issues:
https://apps.apple.com/ch/app/isobmff-explorer/id1300778278?l=en&mt=12

I'm closing the issue for now, feel free to reopen one if you have other questions. : )

**Closed by macmade** 2020-04-20 13:20 UTC
